name: "Music Assistant Proxy"
version: "1.0.0"
slug: "music_assistant_proxy"
description: "Proxy voor Music Assistant met Web Interface"
url: "https://github.com/Sarnog/Music-Assistant-Proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8095]/"
watchdog: "http://[HOST]:[PORT:8095]/"
ingress: true
ingress_port: 8095
ingress_entry: /
panel_icon: "mdi:music"
panel_title: "Music Assistant"
ports:
  8095/tcp: 8095
ports_description:
  8095/tcp: "Web interface (Not required for Hass.io Ingress)"
options:
  server: "http://localhost:8095"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
